name: Deploy Kino Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Bu tugma orqali qo'lda ishga tushirish imkonini beradi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/sardor/kino-bot
            git pull origin main
            source venv/bin/activate || true
            pip install -r requirements.txt || true
            pkill -f main.py || true
            nohup python3 main.py > bot.log 2>&1 &
